### ISSUE TITLE
where is models/DCTmtx.npy

### ISSUE THREAD

**Issue by DayBreak-u** [JuZiSYJ/fancy_operations#1]
hi ，good jobs! Where are the documents models/DCTmtx.npy？please

**Comment by JuZiSYJ** [comment]
Sorry for the delay, the  DCT coefficient init is updated in conv_utils.
I rearrange the coefficient from  low to high frequency.

**Comment by awk333** [comment]
您好，找不到models/DCTmtx.npy，方便提供一下吗？

**Comment by JuZiSYJ** [comment]
Already upload。thanks！
